### ISSUE TITLE
Error savedefconfig does not match ...

### ISSUE THREAD

**Issue by sethleedy** [negroni-development/oneplus-sm8450_t_13.0_10pro#1]
1] Question: is it possible to get make menuconfig running? or what is the best method to change the kernel options.
2] I cloned and ran according to README instructions. Ran into this error.
[oneplus kernel error.txt](https://github.com/negroni-development/oneplus-sm8450_t_13.0_10pro/files/10787000/oneplus.kernel.error.txt)

----

  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
make[1]: Leaving directory '/home/seth/building_images/sources/Kitt-Kernel/oneplus-sm8450_t_13.0_10pro/kernel_platform/out/msm-waipio-waipio-gki/gki_kernel/common'
+ set +x
========================================================
 Running pre-make command(s):
+ eval check_defconfig
++ check_defconfig
++ cd /home/seth/building_images/sources/Kitt-Kernel/oneplus-sm8450_t_13.0_10pro/kernel_platform/out/msm-waipio-waipio-gki/gki_kernel/common
++ make LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc O=/home/seth/building_images/sources/Kitt-Kernel/oneplus-sm8450_t_13.0_10pro/kernel_platform/out/msm-waipio-waipio-gki/gki_kernel/common savedefconfig
  GEN     Makefile
++ '[' arm64 = x86_64 -o arm64 = i386 ']'
++ echo Verifying that savedefconfig matches common/arch/arm64/configs/gki_defconfig
Verifying that savedefconfig matches common/arch/arm64/configs/gki_defconfig
++ RES=0
++ diff -u common/arch/arm64/configs/gki_defconfig /home/seth/building_images/sources/Kitt-Kernel/oneplus-sm8450_t_13.0_10pro/kernel_platform/out/msm-waipio-waipio-gki/gki_kernel/common/defconfig
--- common/arch/arm64/configs/gki_defconfig     2023-02-20 18:12:11.603954526 +0000
+++ /home/seth/building_images/sources/Kitt-Kernel/oneplus-sm8450_t_13.0_10pro/kernel_platform/out/msm-waipio-waipio-gki/gki_kernel/common/defconfig    2023-02-20 18:16:26.963906848 +0000
@@ -92,9 +92,6 @@
 CONFIG_CRYPTO_AES_ARM64_CE_BLK=y
 CONFIG_KPROBES=y
 CONFIG_JUMP_LABEL=y
-CONFIG_SHADOW_CALL_STACK=y
-CONFIG_LTO_CLANG_FULL=y
-CONFIG_CFI_CLANG=y
 CONFIG_MODULES=y
 CONFIG_MODULE_UNLOAD=y
 CONFIG_MODVERSIONS=y
@@ -680,7 +677,6 @@
 CONFIG_PAGE_PINNER=y
 CONFIG_DEBUG_MEMORY_INIT=y
 CONFIG_KASAN=y
-CONFIG_KASAN_HW_TAGS=y
 CONFIG_KFENCE=y
 CONFIG_KFENCE_SAMPLE_INTERVAL=500
 CONFIG_KFENCE_NUM_OBJECTS=63
++ RES=1
++ '[' 1 -ne 0 ']'
++ echo ERROR: savedefconfig does not match common/arch/arm64/configs/gki_defconfig
ERROR: savedefconfig does not match common/arch/arm64/configs/gki_defconfig
++ return 1

**Comment by sethleedy** [comment]
Looking at the repo, I guess it is not all there? This is the first time trying to create a Mobile Kernel compared to a normal Linux kernel. Do I need to merge other repo's?

**Comment by Proxy13** [comment]
@sethleedy sprey for late response .Source has missing Config file. we are waiting force push missing files and drivers by OOSAdmin.When they released i will update repo.

**Comment by sethleedy** [comment]
Thank you.

**Comment by Proxy13** [comment]
@sethleedy  try again mate.if u had any error like this 

++ echo ERROR: savedefconfig does not match common/arch/arm64/configs/gki_defconfig
ERROR: savedefconfig does not match common/arch/arm64/configs/gki_defconfig
++ return 1

just run compilation command again

**Comment by Proxy13** [comment]
@sethleedy 
use this repo it is done now 

https://github.com/negroni-development/OOS-sm8450_t_13.0_10pro

**Comment by sethleedy** [comment]
ah, thank you very much.

I may be able to test it around midnight.
